version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.main:app --reload --host 0.0.0.0
    volumes:
      - .:/happy_milkman
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - postgres

  postgres:
    build:
      context: postgres
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - POSTGRES_USER=${POSTGRES_SUPERUSER}
      - POSTGRES_PASSWORD=${POSTGRES_SUPERUSER_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_SUPERUSER} -p 5454"]
      interval: 3s
      timeout: 5s
      retries: 10
volumes:
  postgres_data: